input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "logger=%{WORD:logger} t=%{TIMESTAMP_ISO8601:time} level=%{WORD:level} msg=\"%{DATA:msg}\" duration=%{DATA:duration}" }
    remove_field => ["host", "agent", "ecs", "log", "input"]
  }
  date {
    match => ["time", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
